from enum import StrEnum


class MeterStatus(StrEnum):
    NORMAL = "NORMAL"
    SUSPECTED_FAULT = "SUSPECTED_FAULT"
    FAULT = "FAULT"
    UNKNOWN = "UNKNOWN"


class CommunicationStatus(StrEnum):
    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    DISCONNECTED = "DISCONNECTED"
    UNKNOWN = "UNKNOWN"


class TelemetrySource(StrEnum):
    SIMULATOR = "SIMULATOR"
    CSV_UPLOAD = "CSV_UPLOAD"
    MQTT_DEVICE_FUTURE = "MQTT_DEVICE_FUTURE"


class AnomalyCause(StrEnum):
    NORMAL = "NORMAL"
    THEFT_TAMPERING = "THEFT_TAMPERING"
    METER_MALFUNCTION = "METER_MALFUNCTION"
    COMMUNICATION_FAILURE = "COMMUNICATION_FAILURE"
    LEGITIMATE_ABNORMAL_CONSUMPTION = "LEGITIMATE_ABNORMAL_CONSUMPTION"
    UNCERTAIN = "UNCERTAIN"
